### ISSUE TITLE
Error when navigating back to a tab that has been closed

### ISSUE THREAD

**Issue by linesarefuzzy** [Tyriar/navigation-history#9] opened 2016-02-07 18:55 UTC
1. Navigate away from a tab
2. Close that tab
3. `navigation-history:back`

**Atom Version**: 1.4.3
**System**: Mac OS X 10.10.5
**Thrown From**: [navigation-history](https://github.com/Tyriar/navigation-history) package, v0.1.8
### Stack Trace

Uncaught Error: Adding a pane item with URI '/[...]/app/helpers/base_crud_helper.rb' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:331

Error: Adding a pane item with URI '/[...]/app/helpers/base_crud_helper.rb' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:331:15)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:315:14)
    at Object.module.exports.jumpTo (/[...]/.atom/packages/navigation-history/lib/main.coffee:42:23)
    at Object.module.exports.jumpBack (/[...]/.atom/packages/navigation-history/lib/main.coffee:29:6)
    at atom-text-editor.disposables.add.atom.commands.add.navigation-history:back (/[...]/.atom/packages/navigation-history/lib/main.coffee:18:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:49.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:46.2.0 navigation-history:back (atom-text-editor.editor.is-focused)
     -0:34.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:34.2.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -0:33 navigation-history:forward (atom-text-editor.editor.is-focused)
  2x -0:30.4.0 navigation-history:back (atom-text-editor.editor.is-focused)
     -0:27.7.0 navigation-history:forward (atom-text-editor.editor.is-focused)
     -0:26.5.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
  2x -0:25.9.0 navigation-history:back (atom-text-editor.editor.is-focused)
  3x -0:24.2.0 navigation-history:forward (atom-text-editor.editor.is-focused)
  2x -0:22.8.0 navigation-history:back (atom-text-editor.editor.is-focused)
     -0:21.9.0 navigation-history:forward (atom-text-editor.editor.is-focused)
  2x -0:21.6.0 navigation-history:back (atom-text-editor.editor.is-focused)
     -0:20.5.0 navigation-history:forward (atom-text-editor.editor.is-focused)
  5x -0:20.1.0 navigation-history:back (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "seti-icons",
      "linter-rails-best-practices"
    ],
    "themes": [
      "one-dark-ui",
      "twilight-syntax"
    ]
  },
  "navigation-history": {}
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.20.0
browser-plus, v0.0.54
emmet, v2.4.1
file-icons, v1.6.14
language-slim, v0.5.0
linter, v1.11.3
linter-bootlint, v1.0.0
linter-csslint, v1.2.0
linter-erb, v1.0.2
linter-htmlhint, v1.0.2
linter-ruby, v1.2.1
linter-slim, v1.0.0
navigation-history, v0.1.8
open-recent, v5.0.0
recent-files-fuzzy-finder, v0.2.4
remote-edit, v1.8.24
symbol-gen, v1.0.0
twilight-syntax, v0.7.0

# Dev
No dev packages
```

**Comment by pchomik** [comment] 2016-02-08 10:03
In my case such problem disappear when I uninstalled emmet package. I don't know why?

**Comment by Tyriar** [comment] 2016-02-08 18:41
Duplicate of https://github.com/Tyriar/navigation-history/issues/7

**Closed as completed by Tyriar** 2016-02-08 18:41 UTC
