### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '/Users/username/Git/path/to/file/file...

### ISSUE THREAD

**Issue by eugenet8k** [Tyriar/navigation-history#11] opened 2016-04-21 00:23 UTC
[Enter steps to reproduce below:]
1. Install https://github.com/Tyriar/navigation-history
2. Close the file where some activity was done
3. Open another file and invoke "Navigate History: Back" command

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [navigation-history](https://github.com/Tyriar/navigation-history) package, v0.1.8
### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/username/Git/path/to/file/file.hbs' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:453

Error: Adding a pane item with URI '/Users/username/Git/path/to/file/file.hbs' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:453:15)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:428:14)
    at Object.module.exports.jumpTo (/Users/username/.atom/packages/navigation-history/lib/main.coffee:42:23)
    at Object.module.exports.jumpBack (/Users/username/.atom/packages/navigation-history/lib/main.coffee:29:6)
    at atom-text-editor.disposables.add.atom.commands.add.navigation-history:back (/Users/username/.atom/packages/navigation-history/lib/main.coffee:18:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:55.7.0 project-find:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:55.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:55 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:01.2.0 navigation-history:back (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-haml",
      "linter-js-standard",
      "color-picker",
      "minimap-split-diff",
      "minimap",
      "linter-stylint-h",
      "react",
      "multirow-tabs"
    ],
    "projectHome": "~/Git/",
    "themes": [
      "native-ui",
      "quiet-light-atom"
    ]
  },
  "navigation-history": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v3.0.0
autoupdate-packages, v1.3.1
better-handlebars, v0.1.1
docblockr, v0.7.3
file-icons, v1.7.4
language-diff, v0.4.0
language-gradle, v0.0.3
language-haml, v0.24.0
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-handlebars, v2.3.4
linter-htmlhint, v1.1.3
linter-js-yaml, v1.2.5
linter-ruby, v1.2.2
linter-stylint, v2.1.2
native-ui, v0.17.0
navigation-history, v0.1.8
pigments, v0.26.0
preview, v0.16.6
project-manager, v2.9.7
quiet-light-atom, v1.5.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by Tyriar** [comment] 2016-04-22 17:29
Duplicate of https://github.com/Tyriar/navigation-history/issues/7

**Closed as completed by Tyriar** 2016-04-22 17:29 UTC

**Comment by eugenet8k** [comment] 2016-04-22 18:04
@Tyriar I see that #7 was closed long time ago (Feb 8), but it happens to me all the time while working on the most recent versions of Atom and navigation-history. Maybe something else causing it...

**Comment by Tyriar** [comment] 2016-04-22 18:05
@eugenet8k Feb 8 was just when another duplicate (#9) was closed, #7 is still open.

**Comment by eugenet8k** [comment] 2016-04-22 18:06
@Tyriar  oh, sorry for confusion. Yes, I see the bug is open now. Wondering if I can help anyhow with this, will take a look.

**Comment by Tyriar** [comment] 2016-04-22 18:09
@eugenet8k no worries. I'd be happy to accept a PR and republish. If you can put something together a test would be great too ([under this suite](https://github.com/Tyriar/navigation-history/blob/master/spec/navigation-history-spec.coffee#L17)).
